name: Build PocketMine Docker image

on:
  push:
    branches:
      - stable
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/pocketmine-mp:latest" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/pocketmine-mp/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}